### ISSUE TITLE
Working with go structs

### ISSUE THREAD

**Issue by apiarian** [karrick/goavro#10]
Do you have plans to support encoding and decoding arbitrary go structs? If not, would you be willing to accept pull requests implementing such functionality?

It would be great to have something like the `encoding/gob` process for building a encoding or decoding kernel on the fly.

Another alternative might be a generator which builds the code for converting to and from the basic types and `interface{}` bits that the library works with.

Mostly looking for something to obviate the tedium of creating lots of conversion code when working with a wide range of kafka topics, without the ability to just use the `gogen-avro` tool or something like it.

**Comment by karrick** [comment]
I suppose there are three ways to tackle the problem you've described:

1. Dynamic encoding and decoding directly to and from user defined structures, although this requires heavy use of reflection that tend to slow down the implementation speed. This method is used by the incredibly flexible `encoding/json` library found in the Go standard library.
1. Code Generation, using struct field tags. This method is used by the incredibly fast https://github.com/pquerna/ffjson library, and the goavro-inspired https://github.com/alanctgardner/gogen-avro library.
1. Dynamic codec creation to native Go types, as this library currently does, conveying complex Avro data types to use Go `map` instances.

If you don't believe me on the speed issue, just compare benchmarks between approach (1) and (2) for non-trivial nested data structures. Using reflection to encode and decode data is amazingly flexible and memory efficient, but incredibly slow.

This library is not purposed with (1) in mind, which is what I believe you are looking for. Sadly I do not know of a different Avro library that does this.

**Comment by apiarian** [comment]
I've been using a fork of the old linkedin/goavro library to process Kafka messages encoded in Avro. I can't really use the pure code generation approach since I don't know what sort of data will be in the topics in advance, and the schemas of the messages per topic can change over time.

So I've been turning the messages into `goavro.RecordSet` structs and then writing a bunch of rather repetitive code to extract the various interesting fields out into my own structs. I've gotten it to the point that I have a helper library to pull specific fields out of the `RecordSet` by a nested name, in the proper base go type (using code generation to handle fields that might be null or arrays or slices of non `interface{}` things).

I was thinking that it might be useful to have a way to include that extra layer of functionality in this package. Though, since you're now turning complex records into `map`s instead of `goavro.Record`s, this might be a task for a dedicated `map` -> `struct` library.
