### ISSUE TITLE
Problem with Namespaces generated by Java Reflect containing a $ sign

### ISSUE THREAD

**Issue by msiuts** [karrick/goavro#11]
We are trying to use goavro with schemas generated via Java and which therefore contain a $ character in the namespace.

We are aware that this is against the Spec and therefore checked by goavro.

Basically the issue is the same as described here:
https://issues.apache.org/jira/browse/AVRO-1478?focusedCommentId=13932200&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13932200

Because as the linked comment says, these schemas are out in the wild and maybe it would be a good feature to support this with some kind of flag when creating the Codec. Do you have any opinions on such a feature?

**Comment by karrick** [comment]
Thanks for the jira link to AVRO-1478. I think the idea is sound and easy enough to do, although I hesitate changing the library to violate the spec.

If the spec is updated to allow the `$` sigil, then I'd be happy to make the change. For now, maybe the best "get it working" solution is to fork the library, and add the `$` to the list of valid namespace symbols. I believe the correct diff is:

```diff
diff --git a/name.go b/name.go
index 88c9100..ebb5d18 100644
--- a/name.go
+++ b/name.go
@@ -25,7 +25,7 @@ func isRuneInvalidForFirstCharacter(r rune) bool {
 }
 
 func isRuneInvalidForOtherCharacters(r rune) bool {
-	return isRuneInvalidForFirstCharacter(r) && (r < '0' || r > '9')
+	return isRuneInvalidForFirstCharacter(r) && (r < '0' || r > '9') && r != '$'
 }
 
 func checkNameComponent(s string) error {
```
