### ISSUE TITLE
feature request: NewCodecFromFile ?

### ISSUE THREAD

**Issue by c0b** [karrick/goavro#4]
in many cases of encoding avro files, the schema definition is saved in a avsc file, would you mind add a wrapper?

https://avro.apache.org/docs/1.7.7/gettingstartedjava.html#Creating+users
```java
Schema schema = new Schema.Parser().parse(new File("user.avsc"));
```

in Go it can be like this:

```go
func NewCodecFromAvsc(path string) (*Codec, error) {
  schema, err := ioutil.ReadFile(path)
  // check err
  return NewCodec(schema)
}
```

let me know if you like a pull request.

**Comment by karrick** [comment]
`NewCodec` was written to accept a string for the contents of the schema, which was pretty generic enough to suit any purpose. 

There are so many potential sources of Avro schema, such as source code comments, program configuration values, schema registry or network service, there would be no way to anticipate and write a helper function for every need. Indeed, the helper function for grabbing the schema from a file would simply be stringing together a standard library call and the `NewCodec` call, checking for errors along the way.

Nevertheless, here are a few helper functions that you might find helpful to copy and use:

```Go
// NewCodecFromRawFile reads the specified file, and returns a Codec generated
// from the schema of file's contents.
func NewCodecFromRawFile(pathname string) (*Codec, error) {
	schemaBytes, err := ioutil.ReadFile(pathname)
	if err != nil {
		return nil, err
	}
	return NewCodec(string(schemaBytes))
}

// NewCodecFromOCF opens the specified OCF file, and returns the Codec from the
// file's metadata.
func NewCodecFromOCF(pathname string) (*Codec, error) {
	fh, err := os.Open(pathname)
	if err != nil {
		return nil, err
	}
	defer func() { _ = fh.Close() }()
	ocf, err := NewOCFReader(fh)
	if err != nil {
		return nil, err
	}
	return ocf.Codec(), nil
}
```
