### ISSUE TITLE
a buffer grow by n bytes internal interface and binary.LittleEndian.PutUint32 / 64 ?

### ISSUE THREAD

**Issue by c0b** [karrick/goavro#7]
it seems my comments on past comments weren't bringing anyone's attention, so open this issue here:
https://github.com/karrick/goavro/commit/28d1d729ea47e84f9d044b0aa1ecf95f1de24fd4#commitcomment-22390799

And today by reading this code I found this technique is already in use in the case CompressionSnappy:
https://github.com/karrick/goavro/blob/master/ocf_writer.go#L159-L164

(BTW, this line #L163 I think can be re-written like this, to avoid constructing a temporary []byte slice)
```go
// OCF requires snappy to have CRC32 checksum after each snappy block
compressed = append(compressed, 0, 0, 0, 0)     // expand slice so checksum will fit
binary.BigEndian.PutUint32(compressed[len(compressed)-4:], ...
```

For primitive types among many places of this library, you may write like `buf = append(buf, 0, 0, 0, 0, 0, 0, 0, 0)` for up to 8 bytes it's still worthwhile, I believe this way of growing buffer capacity + a `binary.LittleEndian.PutUint32/64` call can be still beneficial than a for-loop of multiple append call in current floatingBinaryEncoder;

For any other length of growing, you may want to write a util function to handle
the implementation could be similar to `bytes.Buffer#Grow`
1. https://golang.org/pkg/bytes/#Buffer.Grow
2. https://github.com/golang/go/blob/master/src/bytes/buffer.go#L110

These suggestions may very micro level of optimization, Although I haven't done benchmark yet, want to know your opinion.

**Comment by karrick** [comment]
Really great suggestions!

I'm not going to tackle re-implementing `Buffer.Grow` now, but I'll keep it in mind!

I appreciate the critical eye in the code, and hope to see more suggestions like this!
