### ISSUE TITLE
need a NewOCFWriter from an existing codec?

### ISSUE THREAD

**Issue by c0b** [karrick/goavro#8]
in a typical continuous writing avro files application with rotation, in every rotation it needs to create NewOCFWriter, then the schema string is parsed again and again,

In this scenario, the writer schema is most probably static since program initialization, so why not do once NewCodec at `init` time and have a NewOCFWriter method to `*Codec` ? or add codec parameter to OCFWriterConfig for NewOCFWriter is also ok

BTW: https://github.com/karrick/goavro/blame/master/codec.go#L414 the `typeNames` is no longer in use and can be killed?

**Comment by karrick** [comment]
I'm in the middle of updating the OCFWriter logic right now and finally have some testing on it. My plan was to push tomorrow morning after I write a few more test cases.

You bring up a great use case that I hade never considered. I'll update the config to optionally take an existing goavro.Codec.

Hopefully I can get these changes in tonight or tomorrow morning.

**Comment by karrick** [comment]
I haven't forgotten this request, but got really busy at work today. Hopefully Friday morning gives me a bit of time to wrap up testing and push the updates to this.

**Comment by karrick** [comment]
See example in:

https://github.com/karrick/goavro/blob/master/examples/splice/main.go
