### ISSUE TITLE
would it be better to use crypto/rand/#Read for syncMarker initialization

### ISSUE THREAD

**Issue by c0b** [karrick/goavro#9]
https://golang.org/pkg/crypto/rand/#Read instead of a for-loop to fill the 16 bytes

and syncMarker can be an array instead of slice, you won't need an extra allocation for these 16 bytes, a default `&ocfHeader{}` will get that 16 bytes syncMarker

```go
type ocfHeader struct {
	codec         *Codec
	compressionID compressionID
	syncMarker    [ocfSyncLength]byte
}
```

then at reader initialization: this line https://github.com/karrick/goavro/blob/master/ocf.go#L167 can be changed to

```go
header := &ocfHeader{codec: codec, compressionID: cID}
if _, err := io.ReadFull(ior, header.syncMarker[:]); err != nil {
  // not enough bytes for the syncMarker
}
return header, nil
```

at writer initialization: this for-loop https://github.com/karrick/goavro/blob/master/ocf.go#L95-L99 can be changed to

```go
rand.Read(header.syncMarker[:])
```

**Comment by c0b** [comment]
generally golang slice is more flexible than array in golang, but since slice has to keep ptr/len/cap so whenever the length is known fixed, use array should be more efficient

from array to slice there is one `[:]` operation to convert, but not vice versa

[1] https://blog.golang.org/go-slices-usage-and-internals

**Comment by karrick** [comment]
Thanks, I appreciate your ideas and will incorporate your feedback.

I had used math.Rand rather than crypto rand because there is no need for cryptologically random sync markers. However, there's also no harm in doing so. Also the code suggestions you included in your issue are well thought out. Thanks!

**Comment by karrick** [comment]
fixed by https://github.com/karrick/goavro/commit/a095d4a701f3670a36c38ea193139c07e1546136
